name: Deploy Function App (Flex-safe CLI)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: fn-splunk-wait-box          # Resource name (NO suffix)
  AZURE_RESOURCE_GROUP: Duo                           # Your resource group name
  ZIP_PATH: release.zip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install / build (optional)
        run: |
          npm ci || npm install
          npm run build --if-present

      - name: Create deployment zip
        run: |
          zip -r "$ZIP_PATH" . -x ".git/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-zip
          path: ${{ env.ZIP_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-zip

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy via Azure CLI (works on Flex)
        run: |
          az functionapp deployment source config-zip \
            --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" \
            --name "${{ env.AZURE_FUNCTIONAPP_NAME }}" \
            --src "${{ env.ZIP_PATH }}"
