name: Deploy Function App (Flex-safe)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: fn-splunk-wait-box         # <-- NO suffix here
  AZURE_RESOURCE_GROUP: Duo                          # <-- your RG
  ZIP_PATH: package.zip

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Archive app
        run: |
          zip -r "$ZIP_PATH" . -x ".git/*"

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy via Azure CLI (works on Flex)
        run: |
          az functionapp deployment source config-zip \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --name "$AZURE_FUNCTIONAPP_NAME" \
            --src "$ZIP_PATH"
